# Generated by Django 3.2.6 on 2021-08-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-pk']},
        ),
    ]
